config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  resources :homes, only: :index
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  post '/users/guest_sign_in', to: 'users#new_guest'
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments 
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  mount_uploader :image, ImageUploader

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #comment
  has_many :tweets
  has_many :comments
  #follow
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  #DM
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #いいね
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

  validates :name, presence: true, uniqueness: true
  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  #いいねしているかどうかの判定
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(6).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end
  
  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
    @like = Like.new
  end

  def search
    @tweet = Tweet.find_by(params[:id]) 
    @tweets = Tweet.search(params[:keyword]).page(params[:page]).per(6).order("created_at DESC")
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @realname = @user.realname
    @tweets = @user.tweets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.realname%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.realname %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/tweets/_form.html.erb
<form>
  <div class="form-group">
      <%= form.text_field :name, placeholder: "お店の名前" %>
    <div class ="form-group__image">
      <%= form.file_field :image, placeholder: "Image Url" %>
      <%# アイコン選択で画像選択にする方法 %>
      <%# <%= form.label :image, for: “file-input”, class: “fa fa-file-picture-o” do %> 
      <%# <%= form.file_field :image, style: "display: none;" %>  
    </div>
      <%= form.text_area :text, placeholder: "店舗情報（*必須「住所」　募集人員・待遇など）" , rows: "10" %>
      <%= form.submit "掲載する！"  %>
  </div>
</form>

app/views/tweets/_tweet.html.erb
<div class="tweet col-md-4">
  <div class="more">
    <span><%= image_tag 'arrow_top.png'%><span>
    <ul class="more_list">
      <%# <li>
        <%= link_to '記事詳細', "/tweets/#{tweet.id}", method: :get %>
      <%# </li>  %>
        <li>
      <% if user_signed_in? %>
        <div class="dropdown">
          <!-- 切替ボタンの設定 -->
          <button type="button" class="btn btn-default dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            もっと詳しく
            <span class="caret"></span>
          </button>
          <!-- ドロップメニューの設定 -->
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
            <li><%= link_to "投稿者", user_path(tweet.user)%> </li>
            <li> <%= link_to '記事詳細', "/tweets/#{tweet.id}", method: :get %> </li>
            <%# <% if user_signed_in? && current_user.id == @tweet.user_id %> 
              <%# <li><%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
              <%# <li><%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete</li>  %>
            <%# <% end %> 
          </ul>
        </div><!-- /.dropdown -->
        </li>
      <% end %>
    </ul>
  </div>
   <% if user_signed_in? %>
    <div class="tweet__name">
      <%= link_to tweet.name, tweet_path(tweet.id), method: :get %>
      <%# <%= tweet.name %> 
    </div>
   <% else %>
    <div class="tweet__name">
      <%= tweet.name %> 
    </div>
  <% end %>


  <div class = 'tweet__image'>
    <%= image_tag tweet.image.to_s, :size =>'298x298'%>
  </div>
  
  <div class="tweet__text">
    <%= simple_format(tweet.text) %>
  </div>
  いいね
   (<%= tweet.liked_users.count %>)
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
     <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn btn-warning" %>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn btn-warning" %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        編集する
      </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class = "index__search">
  <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <div class = "index__search__btn">
      <%= form.submit "検索", class: "search-btn" %>
    </div>
  <% end %>
</div>
<div class="tweets">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>
<div class="page">
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        掲載申し込み
      </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/tweets/search.html.erb
<div class = "index__search">
  <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <div class = "index__search__btn">
      <%= form.submit "検索", class: "search-btn" %>
    </div>
  <% end %>
</div>
<div class="tweets">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>
<%= paginate(@tweets) %>

app/views/tweets/show.html.erb
<div class ="contents row">
  <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class="more">
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", class: "btn btn-info" , method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", class: "btn btn-warning" , method: :delete %>
        </li>
      </ul>
    </div>
  <% end %>
  <div class="tweet__name">
      <%= @tweet.name %>
    </div>

    <div class="tweet__image">
      <%# <%= image_tag 'arrow_top.png' %> 
      <%= image_tag @tweet.image.to_s %>
    </div>
    
    <div class="tweet__text">
      <%= simple_format(@tweet.text) %>
    </div>
  </div>

  <div class = "likes">
    <h4>いいね件数: <%= @tweet.likes.count %></h4>
      <div class = "likes__btn">
        <% if current_user.already_liked?(@tweet) %>
          <%= button_to 'いいね削除', tweet_like_path(@tweet), method: :delete %>
        <% else %>
          <%= button_to 'いいね', tweet_likes_path(@tweet) %>
        <% end %>
        <h4>いいねしたユーザー</h4>
        <% @tweet.liked_users.each do |user| %>
          <li><%= user.realname %></li>
        <% end %>
      </div>
  </div>

  <div class="comments">
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.realname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>

  
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <%# <a class="btn" href="/">投稿一覧へ戻る</a> %>
    <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn btn-warning" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>Sign up</h2>
    <%= form_with model: @user, url: user_registration_path, id: 'new_user', class: 'new_user', local: true do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :realname %> <em>(8 characters maximum)</em><br />
        <%= f.text_field :realname, autofocus: true, maxlength: "8" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @validatable %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class = "user-index">
  <% if user_signed_in? %>
    <div class = "user-index__btn">
      <%= link_to "投稿一覧へ", tweets_path, class: "header__right--btn" %>
    </div>
     <h2>ユーザー</h2>
    <div class = "user-index__name">
      <% User.all.where.not(id: current_user.id).each do |user| %>
        <p>
          <%# <%= "id: #{user.id} email: #{user.email}" %> 
          <%= link_to "氏名: #{user.realname}", user_path(user) , class: "user-index__name__show"%>
          <% if current_user.following?(user) %>
            <%= link_to 'フォローを外す', unfollow_path(user.id), class: "btn btn-primary active", method: :POST %>
          <% else %>
            <%= link_to 'フォローする', follow_path(user.id), class: "btn btn-primary active" , method: :POST%>
          <% end %>
          <%# <%= link_to "もっと見る", user_path(user) %> 
        </p>
      <% end %>
    </div>
  <% end %>
</div>


<div class = "top">
 
  
</div>

app/views/users/show.html.erb
<div class = "user_show">
    <%# #DM機能 %>
  
    <h1>ユーザー詳細画面</h1>

    <h3><%= "name: #{@user.realname}" %></h3>

    <% if @user.id == current_user.id %>

    <% else %>
      <% if @isRoom == true %>
        <p><a href="/rooms/<%= @roomId %>" class = "dm-btn">メッセージ</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <%= f.submit "メッセージ" %>
        <% end %>
      <% end %>
    <% end %>




    <%# フォローフォロワー機能実装 %>
    <%# <p><%= "ネーム: #{@user.realname}" %>
    <p><%= "フォロー数: #{@user.follower.count}" %></p>
    <p><%= "フォロワー数: #{@user.followed.count}" %></p>
    <% unless @user == current_user %>
      <% if current_user.following?(@user) %>
        <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
      <% end %>
    <% end %>
    <p></p>

  <div class = "users">
    <div class = "users__follow">
      <h4>フォロー</h4>
        <%# <% @user.following_user.where.not(id: current_user.id).each do |user| %> 
        <% @user.following_user.each do |user| %>
          <p>
            <%= link_to "name: #{user.realname}", user_path(user) %>

            <%# <% if current_user.following?(user) %>
              <%# <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %> 
            <%# <% else %> 
              <%# <%= link_to 'フォローする', follow_path(user.id), method: :POST %> 
            <%# <% end %> 
          </p>
        <% end %>
    </div>


    <div class = "userss__follower">
      <h4>フォロワー</h4>
        <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
          <p>
            <%= link_to "name: #{user.realname}", user_path(user) %>
            <%# <% if current_user.following?(user) %> 
              <%# <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %> 
            <%# <% else %> 
              <%# <%= link_to 'フォローする', follow_path(user.id), method: :POST %> 
            <%# <% end %> 
          </p>
        <% end %>
    </div>
  </div>



    <%# #いいね一覧 %>
    <h4>いいねしている投稿</h4>
      <% @user.liked_tweets.each do |tweet| %>
        <%# <%= tweet.user.realname %> 
        <%= simple_format(tweet.name) %> 
        <%# <%= tweet.content %> 
      <% end %>

    <%# 投稿一覧 %>
    <p><%= @realname %>さんの投稿一覧</p>
      <div class="contents__tweets">
        <% @tweets.each do |tweet| %>
          <div class="contents__tweets__tweet">
            <div class="tweet__name">
              <%= simple_format(tweet.name) %>
            </div>
            
            <div class="tweet__image">
              <%= image_tag tweet.image.to_s %>
            </div>
          
            <div class="tweet__text">
              <%= simple_format(tweet.text) %>
            </div>
          </div>
        <% end %>
      </div>

    <%= link_to "ユーザー 一覧へ戻る", users_path , class: "btn btn-info"%>
    <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn btn-info"%>
</div>